server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_war_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lichaoyu1!Q

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.starwar.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.starwar: DEBUG
    org.springframework.web: INFO


